'use client';

import { useParams } from 'next/navigation';
import { motion } from 'framer-motion';
import Link from 'next/link';
import { ArrowLeft, Tag, Clock, BookOpen } from 'lucide-react';

const fadeInUp = {
   initial: { opacity: 0, y: 30 },
   animate: { opacity: 1, y: 0 },
   transition: { duration: 0.8 },
};

const articles: Record<string, {
   title: string;
   category: string;
   readTime: string;
   date: string;
   intro: string;
   image: string;
   body: { heading?: string; text: string }[];
}> = {
   "why-global-peace-is-not-a-dream": {
      title: "Why Global Peace Is Not a Dream — It Is a Human Calling",
      category: "Peace & Advocacy",
      readTime: "12 min read",
      date: "March 2025",
      image: "/blog-images/peace.png",
      intro: "The question of whether global peace is attainable has occupied the minds of philosophers, theologians, and statesmen for millennia. To many, it remains a beautiful but naive aspiration — spoken of at podiums, prayed for in pews, and ultimately set aside as political reality intrudes. But Lord Professor Dr. Kingsley Kebiru Momodu, whose doctoral research and lifework centres on this very question, has arrived at a different and more urgent conclusion: global peace is not an idealist fantasy. It is a calling inscribed into the very nature of the human person.",
      body: [
         {
            heading: "The Spiritual Roots of the Peace Imperative",
            text: "To understand why global peace is a calling rather than a dream, we must first go to where all callings originate — to the nature of God and His design for creation. The Hebrew word shalom, often translated merely as 'peace,' is in fact a far richer concept. It speaks of wholeness, completeness, and the alignment of all things with their intended purpose. When God looked upon creation and declared it 'good,' He was affirming a state of shalom — a universe at peace with its Creator, with itself, and with every living thing within it.\n\nThis was not an accident of language. It was a statement of divine intent. God's original design for humanity was not conflict, division, fear, or war. His design was flourishing — communities of people living in right relationship with God and with one another. The fall introduced rupture into this design. But the entire arc of Scripture from Genesis to Revelation is, at its heart, the story of God restoring what was broken. The Messiah is called the Prince of Peace, not merely as a title, but as a mission statement. Where He comes, shalom follows. The peace that Jesus brings is not the absence of conflict alone — it is the restoration of divine order, of right relationship, of wholeness.\n\nTo pursue global peace is therefore not a political project. It is a spiritual one. It is participation in God's own work of restoration in the world."
         },
         {
            heading: "What History Tells Us About Human Longing",
            text: "If one surveys history with an honest eye, they will find something remarkable beneath all its violence and struggle: a persistent and universal longing for peace. This longing is inscribed into the soul of every culture that has encountered the living God and found in Him the source and destination of all true peace.\n\nSt. Augustine, reflecting on his own restless journey toward God, articulated what countless men and women before and after him have experienced: 'our hearts are restless until they rest in Thee.' That restlessness is not merely a private spiritual aching — it expresses itself in the collective human yearning for a world without war, without hunger, without dehumanisation. The longing for peace is hard-wired into the human soul because we were made for it. The image of God — the Imago Dei — that every person bears is an image that includes the capacity and the desire for shalom.\n\nThe great Christian visionaries of history — from the early Church fathers who refused violence, to the medieval theologians who developed just war theory precisely to limit conflict, to the abolitionists who ended the slave trade on Biblical grounds, to the civil rights preachers who marched with Scripture on their lips — all drew from the same conviction: that the God of the Bible is a God of peace, and that His people are called to embody and extend that peace in the world.\n\nDr. Momodu, in his doctoral research at Kennedy University of Baptist, argues that this persistent longing is itself one of the strongest evidences that peace is achievable — because a longing without any possibility of fulfilment would be a cruel design flaw in human nature, and God is not cruel. The longing exists because it points toward something real."
         },
         {
            heading: "The Peacemaker's Calling: A Biblical Mandate",
            text: "Among the most revolutionary statements in the Sermon on the Mount is Matthew 5:9: 'Blessed are the peacemakers, for they shall be called children of God.' Note what Jesus does not say. He does not say 'blessed are the peaceful' — those who avoid conflict by passive withdrawal. He says 'blessed are the peacemakers' — those who actively enter into situations of tension and work to bring about reconciliation, healing, and restoration.\n\nThe word 'peacemaker' in Greek is eirenopoios — one who does or makes peace. It is an active, creative verb. It implies agency, effort, sacrifice, and skill. To be a peacemaker is to engage with the broken places of the world and labour, often at great personal cost, to see them made whole.\n\nThroughout Dr. Momodu's ministry — from the youth of Lagos to the halls of London, from community halls in Romford to university lecterns across Europe — he has insisted on this active dimension of peacemaking. 'Peace does not fall from the sky into passive hands,' he has written. 'It is built, brick by brick, in the hearts and communities of those who dare to believe that things can be different.'\n\nThe calling of the peacemaker is therefore not reserved for diplomats and heads of state. It is the vocation of every believer who takes the Sermon on the Mount seriously. Every act of forgiveness is an act of peacemaking. Every instance of choosing dialogue over hostility, of extending dignity to the marginalised, of refusing to dehumanise the other — these are acts of peacemaking. Global peace begins in local hearts."
         },
         {
            heading: "Barriers to Peace — and Why They Are Not Final",
            text: "It would be intellectually dishonest to speak of global peace without acknowledging the magnitude of the obstacles before it. Wars rage on multiple continents. Ethnic hatreds calcified over generations resist every diplomatic effort. Economic systems that structurally advantage the wealthy and dispossess the poor generate the conditions in which violence flourishes. Religious extremism, nationalism, tribalism, and the trauma of historical injustices all feed the cycle of conflict.\n\nDr. Momodu is not naïve about these realities. His ministry has taken him to the palaces of the powerful and the dwellings of the destitute. He has sat with those consuming war and with those consumed by it. He is not offering a simplistic gospel that refuses to reckon with human darkness. He is, rather, offering a theological and practical conviction that no barrier, however entrenched, is more powerful than the redemptive grace of God working through willing human agents.\n\nHistory bears this out. The abolition of the transatlantic slave trade was once considered politically impossible — until it wasn't. Apartheid South Africa was expected to end in a bloodbath — and yet emerged, imperfectly but remarkably, through the extraordinary grace of men and women willing to choose peace over vengeance. The Northern Ireland peace process confounded every cynic. These were not the achievements of utopian idealists. They were the fruit of hard, patient, costly peacemaking — often driven by people of deep faith who refused to accept that human destiny was fixed in darkness."
         },
         {
            heading: "A Practical Theology of Peace",
            text: "What, then, does a practical theology of global peace look like for the ordinary believer? Dr. Momodu offers several interconnected principles rooted in his ministerial experience:\n\nFirst, peace must be cultivated inwardly before it can be extended outwardly. A person at war with themselves — with their past, their identity, their God — cannot authentically build peace in their community. Inner healing is not a luxury. It is the prerequisite for peacemaking. This is why the global peace ministry takes healing prayer and pastoral support as seriously as its advocacy work.\n\nSecond, peace requires listening. The peacemaker must be one who is slow to speak and quick to hear — who can sit with the grievance of the other without immediately defending or dismissing. Much of what passes for dialogue in our world is simply parallel monologues. True peace-building requires the discipline of genuinely hearing the other's pain.\n\nThird, peace demands justice. The prophet Isaiah makes clear that there is no peace without justice — shalom is inextricably linked to righteousness. A peace that merely asks the oppressed to stop complaining while leaving the structures of oppression in place is not peace. It is management. Global peace ministry therefore involves advocacy for the poor, the voiceless, the forgotten — not merely as a social project but as a spiritual imperative.\n\nFinally, peace is always sustained by prayer. Not prayer as a substitute for action, but prayer as the source of the vision, courage, and perseverance that action requires. Dr. Momodu has prayed in more cities, nations, and contexts than most ministers will visit in a lifetime. He carries with him the absolute conviction that prayer changes things — not as a platitude but as a demonstrated reality."
         },
         {
            heading: "The Invitation",
            text: "Global peace is not a dream reserved for the powerful or the privileged. It is a calling extended to every human being who bears the image of God. It begins not with governments or grand summits but in the hidden choices of ordinary people — to forgive, to listen, to refuse hatred, to advocate for the forgotten, to pray without ceasing.\n\nAt Global Peace Ministry, we believe that God is raising up peacemakers in every nation, every culture, and every generation. We believe that the same Spirit that hovered over the waters at creation and brought order from chaos is still moving — in Romford and in Nairobi, in Washington and in Warsaw, in the smallest village and the largest metropolis.\n\nYou are invited to be part of this movement. Not because it is easy. But because it is true. And because there is no more worthy calling to which a human life can be given than to this ancient, urgent, irreplaceable work: the making of peace."
         },
      ]
   },
   "the-power-of-prayer-in-a-world-at-war": {
      title: "The Power of Prayer in a World at War",
      category: "Prayer & Faith",
      readTime: "11 min read",
      date: "February 2025",
      image: "/blog-images/prayer.png",
      intro: "We live in an age of extraordinary global tension. News cycles deliver a near-constant stream of wars, uprisings, humanitarian disasters, and political instability. The temptation, for many believers, is to feel overwhelmed — to conclude, privately, that prayer in the face of such forces is naïve, or worse, futile. This article argues the opposite: that intercessory prayer is one of the most powerful forces for real-world change ever documented in human history, and that its necessity has never been greater than it is today.",
      body: [
         {
            heading: "The Historical Evidence for Prayer's Power",
            text: "Before we speak theologically, let us speak historically. The evidence for prayer changing the course of nations is not merely a matter of faith — it is a matter of recorded fact.\n\nConsider the miraculous deliverance of Dunkirk in 1940. Britain stood at the precipice of catastrophic military defeat. Over 330,000 Allied troops were surrounded by German forces on the beaches of northern France. King George VI called the nation to prayer. Churches across Britain filled. And what happened next confounded military historians for decades: an extraordinary calm settled over the English Channel — unprecedented for the season — allowing a flotilla of civilian vessels to complete one of the most improbable rescues in military history. Even Winston Churchill, a man not given to sentimentality about religion, described Dunkirk as a 'miracle of deliverance.'\n\nMove further back in history. The Protestant Reformation, which reshaped the entire social and political fabric of Western civilisation, was carried not primarily by armies or treaties but by communities of prayer. The Welsh Revival of 1904-05, sparked largely through the intercessions of Evan Roberts, is documented to have transformed entire Welsh valleys in months — crime rates dropped, pubs emptied, police forces reported near-unemployment in some districts. These are verifiable historical events."
         },
         {
            heading: "Biblical Foundations: Intercession as Authority",
            text: "The Biblical basis for intercessory prayer begins in the very structure of creation. God, in His sovereign wisdom, chose to govern the world not as a divine autocrat who bypasses human agency, but as a Father who invites His children into partnership. 'Ask, and it shall be given to you,' Jesus instructed. 'Seek, and you shall find.' The language of seeking implies that something responds to being sought — that the universe is relationally structured in a way that prayer unlocks.\n\nThe prophet Ezekiel records one of the most startling statements in all of Scripture. God declares that He 'looked for a man among them who would build up the wall and stand before Me in the gap on behalf of the land so I would not have to destroy it, but found none' (Ezekiel 22:30). What this passage implies is that divine judgment was available to be averted — but the means by which it could have been averted was human intercession. When no intercessor was found, history took a darker path.\n\nThis is a staggering theological claim. It places intercessory prayer not at the periphery of human agency in history but at its very centre. Nations rise and fall not only because of economic forces, military might, and political decisions — they rise and fall because of the prayers that are or are not offered on their behalf.\n\nThe Apostle Paul, writing to Timothy, was not being merely polite when he urged 'that petitions, prayers, intercession and thanksgiving be made for all people — for kings and all those in authority, that we may live peaceful and quiet lives in all godliness and holiness' (1 Timothy 2:1-2). He was articulating a cosmic strategy: that the prayers of the Church shape the conditions in which peace becomes possible."
         },
         {
            heading: "What Intercession Actually Does",
            text: "There is sometimes a misunderstanding about what intercessory prayer is and how it works. Some imagine it as a kind of spiritual bribery — accumulating enough prayer to tip the divine scales in a desired direction. Others reduce it to a psychological exercise in self-comfort, helping the pray-er feel less helpless without actually changing anything external.\n\nBoth of these frameworks miss what Scripture actually describes. Intercession, in the Biblical model, is participation in divine governance. The intercessor stands in the breach — in the gap between the way things are and the way God intends them to be — and through prayer creates a channel through which divine grace can flow into a situation.\n\nWhen we pray for a war-torn nation, we are not merely expressing our hope that things improve. We are, in a real and spiritually significant sense, deploying spiritual authority into that situation. We are inviting the Kingdom of God — its justice, its healing, its reconciliation — to bear upon a situation that has thus far resisted it. We are partnering with the Holy Spirit, who intercedes through us 'with groanings too deep for words' (Romans 8:26), in the divine work of restoration.\n\nDr. Momodu, who has prayed over conflicts in sub-Saharan Africa, in European cities, and in community settings across London, speaks of intercession as 'standing in history on behalf of those who cannot stand for themselves.' He describes moments in prayer where the weight of a nation's suffering settles on the intercessor, and the prayer that emerges is not polished or articulate but raw, genuine, and powerful — the prayer that moves heaven."
         },
         {
            heading: "Prayer Movements That Changed Nations",
            text: "Beyond individual intercession, church history is marked by organised prayer movements that produced documentable transformations.\n\nThe Moravian Brotherhood, beginning in 1727, launched what historians regard as the first round-the-clock prayer watch in recorded Christian history. From their community in Herrnhut, Germany, they maintained continuous intercession in rotating shifts — and this movement, sustained for over one hundred years, gave birth to the modern Protestant missionary movement. More missionaries went out from this small community of fewer than three hundred people than had gone out from the entire Protestant world in the preceding two centuries. Prayer fuelled the most significant missionary expansion in history.\n\nIn our contemporary era, South Korea's prayer movement is perhaps the most dramatic modern parallel. Korean Christians are renowned worldwide for their commitment to early-morning prayer — gatherings that begin at four or five in the morning and can draw thousands to church prayer halls before dawn. The revival that transformed South Korea from a war-devastated nation into one of the most Christianised countries in the world, with one of the world's fastest-growing churches, is inseparably linked to this culture of radical intercession.\n\nThe lesson is consistent across centuries and continents: where God's people pray with focus, faith, and persistence, history bends."
         },
         {
            heading: "Practical Intercession: How to Pray for the World",
            text: "Knowledge of prayer's power must translate into practice. For many believers, the question is not whether prayer works but how to pray when the scale of the world's needs feels overwhelming.\n\nDr. Momodu offers a framework he has used across his decades of ministry. Begin with worship — acknowledging who God is before you begin addressing what the world is. A prayer that begins with lament, while understandable, can become trapped in describing the problem. A prayer that begins with worship establishes the ultimate frame: that God is sovereign, that He is good, that He is still in control.\n\nFrom worship, move to specific intercession. Choose one nation, one conflict, one people group, one situation. The tendency to pray vaguely for 'peace in the world' produces proportionally vague results. Specific prayer — naming a nation, its leaders, its people, the specific issues — is prayer that engages. Use the weekly news not as a source of despair but as a prayer list.\n\nPray with Scripture. The Psalms, in particular, are an inexhaustible resource for intercessors. When language fails, the Psalmist's language rarely does. Praying Psalm 46 ('God is our refuge and strength, an ever-present help in trouble') over a war zone connects the situation to an eternal promise with the full weight of divine authority behind it.\n\nFinally, pray with others. The Matthew 18:20 principle — 'where two or three gather in My name, there I am with them' — suggests a multiplication of divine presence in communal prayer. Intercession is not only a solitary discipline. It is a community practice. Find or form a prayer group committed to interceding for the peace of the world."
         },
         {
            heading: "Do Not Grow Weary",
            text: "The parable of the persistent widow in Luke 18 is Jesus's explicit answer to the temptation to give up in prayer. The widow who came continually to the unjust judge — without status, without power, without leverage — eventually received justice through sheer persistence. 'How much more,' Jesus argues, 'will God bring about justice for His chosen ones who cry out to Him day and night? Will He keep putting them off?'\n\nThe answer is no. He will not keep putting them off. But the fullness of His answer requires the fullness of our asking.\n\nIn a world at war, the people of God are called not to silence but to intercession. Not to despair but to faith. Not to the conclusion that nothing can be done, but to the conviction — rooted in Scripture, confirmed by history, alive in the present — that prayer is among the most consequential things that can be done.\n\nThis is the call that Global Peace Ministry issues to believers everywhere: take up the discipline of intercession. Stand in the gap for your nation, for distant lands, for the suffering and the proud alike. You may never know, on this side of eternity, what your prayers have moved. But this much is certain: they have moved something."
         },
      ]
   },
   "understanding-your-calling": {
      title: "Understanding Your Calling: How to Discover Why God Created You",
      category: "Discipleship & Purpose",
      readTime: "11 min read",
      date: "January 2025",
      image: "/blog-images/calling.png",
      intro: "There are few questions that press more persistently upon the human soul than this one: why am I here? What is the purpose of my life? For many people, this question surfaces in moments of transition — at a career crossroads, in the aftermath of loss, in the quiet hours when the noise of daily life settles and something deeper asserts itself. For the believer, this question is not a philosophical puzzle without an answer. It is an invitation — from a God who fashioned each person with intention and purpose — to discover and step into the life you were uniquely designed to live.",
      body: [
         {
            heading: "God Does Not Work in Generalities",
            text: "The opening chapters of Scripture establish something essential: God is a God of particulars. He does not create in bulk or think in categories. He names the stars individually. He knit you together in your mother's womb — not your category, not your demographic, but you. Psalm 139 records with breathtaking specificity that 'your eyes saw my unformed body; all the days ordained for me were written in your book before one of them came to be.'\n\nThis means that your calling is not generic. God's purpose for your life is not 'be a good Christian person and help others where you can.' That may be the broad shape of all Christian vocation, but within it is a specific expression — a particular constellation of gifts, experiences, passions, and opportunities that, taken together, describe what only you can contribute to the world.\n\nThis is a liberating truth, though it becomes uncomfortable when we begin to pursue it seriously. It is easier, in many ways, to live as though vocation is someone else's concern — reserved for pastors and missionaries and people with obvious dramatic callings. The ordinary person working a job they find merely tolerable, raising children as best they can, attending church on Sundays, might assume that calling is not really for them. This is a profound mistake. God does not create without purpose."
         },
         {
            heading: "Three Dimensions of Calling",
            text: "When we speak of 'calling,' it is helpful to identify what we mean, because the term carries several distinct dimensions that are often conflated.\n\nThe first is the general call — the vocation that belongs to every believer equally. Every person in Christ is called to love God and their neighbour, to bear witness to the Gospel, to pursue justice and love mercy. This is not optional for any Christian, whatever their particular gifts or station in life.\n\nThe second is the specific call — the particular domain, gift, or mission to which an individual is uniquely equipped and summoned. This is the call that Dr. Momodu describes as the 'assignment' — the particular piece of the divine work in the world that has your name on it. It may unfold through a profession, a geography, a relationship network, or a set of experiences that make you uniquely capable of something the world needs.\n\nThe third is the situational call — the contextual, season-specific invitations that come throughout a life. God called Abraham to leave Ur in chapter 12 of Genesis, but the same Abraham who responded to that call was also called, decades later, to the near-sacrifice of Isaac. The second call presupposed the faithfulness exercised in the first. Life is not a single calling so much as a series of increasingly clarified invitations that build on one another.\n\nUnderstanding this layered structure of calling helps prevent two common errors: mistaking the general call for the entirety of vocation, and expecting a once-for-all dramatic revelation of purpose that will make all future decisions self-evident — when in fact calling is often unveiled gradually through faithful small steps."
         },
         {
            heading: "The Map Within: Gifts, Passions, and Fruit",
            text: "One of the most practical contributions to the question of calling comes from understanding your God-given design. The Apostle Paul writes extensively about spiritual gifts — 'different kinds of gifts, but the same Spirit' (1 Corinthians 12:4). These gifts, distributed sovereignly by the Holy Spirit, are not merely tools for church use. They are clues to calling. They describe the shape of how God has equipped you to serve.\n\nBut gifts alone do not complete the picture. Alongside your gifts exists something equally important: your God-given passions. What breaks your heart? What injustice, if you dwell on it, generates in you not merely sadness but a fire? What need in the world, if you think about going a year without addressing it, fills you with a sense of wasted life? These strong emotional responses are not accidental. They are given by God as signposts toward the work He has set aside for you.\n\nThere is a third element: fruit. Where do you see disproportionate return on your effort? Where does your engagement seem to multiply impact in ways that surprise even you? The parable of the talents suggests that God's investment in us is calibrated to what we have been entrusted with — and that the place where our gifts and diligence generate the greatest fruit is often the place we are most called to invest ourselves.\n\nThe intersection of gift, passion, and fruitfulness is a remarkably reliable map of calling. It does not make the path easy. But it makes the territory navigable."
         },
         {
            heading: "The Role of Community and Confirmation",
            text: "One of the greatest errors in contemporary Christianity's approach to calling is excessive individualism. We treat the discovery of calling as a purely private transaction between the individual and God, to be received in solitude and carried out largely alone. But the Biblical pattern is consistently communal.\n\nWhen the early church in Antioch was directed by the Holy Spirit to set apart Paul and Barnabas for the work to which they had been called (Acts 13:1-3), the calling was given to the gathered community in prayer and confirmed through communal consent. When Timothy was recognised for his gifts and his calling, Paul writes that 'prophetic utterances' about him pointed the way, and a council of elders laid hands on him to commission what those words had first discerned (1 Timothy 4:14).\n\nThis means that part of how we discover our calling is by submitting ourselves to wise, loving community that can see us clearly. The people who know us well — who have observed us over time, who have seen both our gifts and our blind spots — are equipped to confirm or question what we think we might be called to. This is not a denial of personal discernment. It is its essential safeguard. Many people who have pursued what they believed to be a personal calling in isolation from accountable community have discovered, too late, that what they mistook for calling was ego, or avoidance, or wishful thinking.\n\nDr. Momodu emphasises that the ministry to which he has devoted his life was not self-declared. It was confirmed — through the affirmation of spiritual leaders, through the response of those he served, through doors that opened in ways that could not be attributed to personal ambition or strategy. Calling, properly understood, is always confirmed outwardly even when it is first received inwardly."
         },
         {
            heading: "When Calling Is Costly",
            text: "No honest treatment of calling can avoid the reality that genuine calling is costly. Jesus did not promise His disciples fulfilling careers that perfectly aligned with their personal interests. He promised a cross. The very structure of New Testament calling is cruciform — it follows the pattern of the One who was called to lay down His life for the world.\n\nThis does not mean that calling is joyless. To the contrary, those who are living in their calling consistently report a quality of deep satisfaction that is entirely different from the surface-level happiness that comes from comfort or convenience. There is a joy in suffering for the right thing, in enduring difficulty in service of a purpose larger than yourself, that cannot be obtained any other way.\n\nBut calling must be distinguished from presumption. Not every difficult path is a calling. Not every sacrifice you choose to make is a God-ordained one. Discernment requires prayer, counsel, and honest self-examination. Have you been faithful with small things before pursuing a large vision? Have you submitted to legitimate authority rather than bypassing it in the name of a supposedly higher vision? Is the fruit of your proposed calling recognisable to those whose judgment you respect?\n\nThese questions are not obstacles to calling. They are the testing that separates genuine calling from its imitations and prepares the one who is called to carry the weight of what they are being asked to do."
         },
         {
            heading: "Stepping In: Practical First Steps",
            text: "If you sense the pull of a calling you have not yet stepped into, the path forward is rarely dramatic. It almost never begins with a resignation letter and a one-way ticket somewhere. It begins with fidelity — to prayer, to small acts of service in the direction of what you sense, to the cultivation of the gifts you already have.\n\nBegin by praying the prayer that Thomas à Kempis attributed to every sincere disciple: 'Lord, what would You have me to do?' Make this not a one-time question but a daily posture. Journal what comes in response — not only flashes of inspiration but the quiet, consistent themes that re-emerge across months and years.\n\nSeek a mentor or spiritual director who has walked further along your vocational road than you have. Learn from them. Allow them to speak into your life. Submit your aspirations to their wisdom.\n\nServe, even before you feel fully ready. Calling is often crystallised not in waiting but in doing. The doing reveals gifts you did not know you had. It generates fruit that confirms the direction. It puts you in the path of people and opportunities that, in the sovereignty of God, have been waiting for your arrival.\n\nYou were not placed on this earth by accident. God knew you before you were formed. He prepared works for you to walk in before the foundation of the world (Ephesians 2:10). The discovery of those works is among the great adventures of the human life. Do not be afraid to begin it."
         },
      ]
   },
   "forgiveness-across-faiths": {
      title: "The Gospel of Forgiveness: How Grace Changes Everything",
      category: "Personal Testimony & Peace",
      readTime: "13 min read",
      date: "December 2024",
      image: "/blog-images/forgiveness.png",
      intro: "Of all the revolutionary truths at the heart of the Christian Gospel, none is more world-altering than this: that the God of the universe, in the person of Jesus Christ, has fully, freely, and finally forgiven every person who turns to Him in faith. This is not a peripheral doctrine. It is the centre of the Gospel. And it has consequences — for how we see ourselves, for how we treat others, and for how nations are built and rebuilt in the aftermath of conflict. This article is a reflection by Lord Professor Dr. Kingsley Kebiru Momodu on what forgiveness has meant in his own life, in his ministry, and in the communities he has served across four continents.",
      body: [
         {
            heading: "The Cross Is the Answer to Every Wound",
            text: "I have sat in rooms where the wounds were very old and very deep. Rooms in which families had not spoken for decades. Communities in which ethnic hatred had calcified into something almost constitutional — a grudge so long held that no one living could fully remember its origin, only its weight.\n\nIn every such room, I have brought the same word. Not a political solution. Not a therapeutic framework. The Cross.\n\nBecause what the Cross of Jesus Christ declares is the one thing that no human institution, negotiation, or philosophy can produce: that the ultimate debt has been paid. That God Himself has absorbed the cost of wrongdoing in His own body, and that the result — for all who receive it — is a full and irreversible cancellation of debt.\n\nPaul writes in Colossians 2:14 that God has 'cancelled the charge of our legal indebtedness, which stood against us and condemned us; He has taken it away, nailing it to the cross.' This is not poetry. It is a legal declaration with cosmic implications. And it is the foundation upon which all genuine human forgiveness is built — not as an independent moral achievement, but as an overflow of what has already been received."
         },
         {
            heading: "Why Forgiveness Is So Hard — and So Necessary",
            text: "To understand why forgiveness is so difficult, we must first understand what unforgiveness actually costs. The person who cannot forgive is not, as they might imagine, holding the one who wronged them in a prison of accountability. They are, in fact, imprisoning themselves — tethered to the moment of wounding, unable to move beyond it, consuming enormous emotional and spiritual energy in the maintenance of a grievance that has already happened and cannot be undone.\n\nJesus understood this. The parable of the unforgiving servant in Matthew 18 is one of His most psychologically precise teachings. The servant who has just been forgiven an unpayable debt — millions in modern equivalent — turns and seizes a fellow servant by the throat over a trivial sum. The absurdity is the point. When we have received the forgiveness of God for the totality of our sin — a debt we could never repay — the withholding of forgiveness from those who wrong us is not only morally wrong. It is spiritually incoherent. It fails to understand what has happened to us.\n\nForgiveness is necessary not primarily because the one who wronged you deserves it. They may not. It is necessary because you were designed for freedom, and unforgiveness is a chain. And it is necessary because the world cannot be at peace when its people are at war with one another in the deepest chambers of their hearts."
         },
         {
            heading: "Forgiveness in Scripture: A Portrait",
            text: "The Bible does not offer a theory of forgiveness. It offers a portrait — painted across its entire length, in stories of extraordinary grace that are designed not merely to inspire but to instruct.\n\nConsider Joseph. Sold into slavery by his own brothers out of jealousy. Wrongly imprisoned. Forgotten. And yet, when the wheel of history turns and those same brothers stand before him trembling in the court of Egypt, what comes from Joseph's lips is not judgment but tears — and the most breathtaking declaration of grace in the Hebrew Scriptures: 'You intended to harm me, but God intended it for good' (Genesis 50:20). Joseph's forgiveness is not the product of amnesia or denial. He knows exactly what was done to him. But he has placed that knowledge within a larger frame — the sovereignty of God — and found, within that frame, the freedom to release his brothers from the debt they could never repay.\n\nConsider the father in the parable of the prodigal son (Luke 15). The son who demanded his inheritance early — essentially wishing his father dead — spent it in reckless living and returned in humiliation. The father, who had every right to offer only the status of a hired servant, instead runs to meet his returning son, robes him, rings him, kills the fatted calf. The forgiveness precedes the apology. The embrace comes before the explanation. This is what God's forgiveness looks like — extravagant, unhesitating, wholly gracious.\n\nAnd consider Jesus Himself on the Cross, in agony, uttering the words that have echoed through Christian history ever since: 'Father, forgive them, for they do not know what they are doing' (Luke 23:34). In the very act of being murdered, He practised what He had always preached. His forgiveness was not conditional on their repentance. It was an act of will, rooted in love, offered freely."
         },
         {
            heading: "Forgiveness Does Not Mean Forgetting",
            text: "One of the most common and most damaging misunderstandings of the doctrine of forgiveness is the equation of forgiveness with forgetting, or the demand that the forgiven person immediately receive full trust and unrestricted access.\n\nThis is not what the Bible teaches. In Dr. Momodu's pastoral experience across decades of ministry — in Africa, in Europe, in the UK — he has consistently had to distinguish between forgiveness as a spiritual release and restoration as a relational process.\n\nForgiveness is something you confer. It is a decision you make, rooted in the grace you have yourself received, to release the person who wronged you from the debt of their offence. It does not require that they apologise, though apology helps. It does not require that the relationship immediately return to what it was before the wound. And it certainly does not require that you expose yourself again to patterns of harm that have not been genuinely repented of and changed.\n\nRestoration, by contrast, is something that is built — over time, through demonstrated change, through the slow rebuilding of trust. The prodigal son was forgiven the moment his father saw him on the road. But the journey of rebuilding — of learning what it meant to live as a son rather than a runaway — took the rest of his life.\n\nThis distinction matters enormously in the communities Global Peace Ministry serves. Those who have survived domestic violence, tribal conflict, communal betrayal, or institutional abuse need to know that God's call to forgive is not a command to be re-victimised. It is a call to freedom — for them. The abuser's accountability before God and, where appropriate, before the law, is a separate matter."
         },
         {
            heading: "Forgiveness as the Foundation of Peacemaking",
            text: "In Dr. Momodu's decades of peace ministry across Africa, Europe, the Americas, and Asia, he has arrived at one of the most consistent conclusions of his vocational life: that no lasting peace is built without forgiveness at its foundation.\n\nThis is not a pious platitude. It is a practical reality that history repeatedly confirms. The peace process that ended apartheid in South Africa was grounded, crucially, in the Christian convictions of its key architects — including Archbishop Desmond Tutu, whose Truth and Reconciliation Commission was explicitly modelled on the Biblical understanding that truth must be told and forgiveness must be extended for genuine healing to occur. Tutu's now-famous phrase — 'there is no future without forgiveness' — is not a slogan. It is a theological conviction drawn from the deepest wells of Christian teaching.\n\nSimilarly, the Northern Ireland Peace Process — imperfect, fragile, still incomplete — was enabled in significant measure by Christian leaders on both sides who chose to meet across the table of the Lord's Supper and discover that what they shared in Christ was greater than what divided them in history.\n\nPeacemaking without forgiveness is, at best, the management of hostility. It keeps combatants from each other's throats but leaves the underlying wounds untouched, the resentments intact, ready to be reignited by the next political provocation. Only forgiveness — the radical, Christ-rooted decision to release the debt — changes the underlying reality. Only forgiveness makes new futures possible."
         },
         {
            heading: "An Invitation: Receive, Then Release",
            text: "I close with the invitation that underlies everything I have written, and everything Global Peace Ministry stands for.\n\nBefore you can forgive, you must know that you have been forgiven. Not in a generic, theological sense — but personally, specifically, completely. The God who made you knows every thought you have ever had that you are ashamed of. Every failure of love. Every act of selfishness or cruelty or cowardice. He knows it all. And in Christ, at the Cross, He has forgiven it all. Not because you deserve it. Because He is love, and love chooses to bear what justice requires rather than destroy what it loves.\n\nWhen that forgiveness lands — really lands — in the interior of a person's life, it transforms them. Not gradually, but fundamentally. Because you cannot truly know that you have been forgiven a debt you could never repay and remain unwilling to release the far smaller debts that others owe you.\n\nI have seen this transformation happen. I have seen men who had carried unforgiveness like a stone for thirty years lay it down in a moment of prayer and walk out of the room visibly lighter. I have seen communities separated by violence begin to share a table because Christ met them both at His table first.\n\nForgiveness is not the easy path. It is not the path of least resistance. It is the path of the Cross — costly, deliberate, supernaturally empowered. But it is the only path that leads where we actually want to go: to lives of freedom, to communities of wholeness, to a world in which the peace of God, which passes all understanding, guards our hearts and minds in Christ Jesus."
         },
      ]
   },
   "what-the-bible-says-about-poverty": {
      title: "What the Bible Says About Poverty and Our Responsibility",
      category: "Charity & Service",
      readTime: "10 min read",
      date: "November 2024",
      image: "/blog-images/poverty.png",
      intro: "Poverty is among the oldest and most persistent challenges of human civilisation. Despite extraordinary technological and economic progress over the past century, hundreds of millions of people across the world still lack access to adequate food, clean water, housing, healthcare, and education. For the Christian, this is not merely a social policy concern — it is a theological one. The Bible speaks about poverty with a frequency and urgency that cannot be honestly ignored, and it speaks with equal directness about what God expects of those who follow Him in response to it.",
      body: [
         {
            heading: "God's Passionate Concern for the Poor",
            text: "Any reading of Scripture that takes the whole text seriously must reckon with the overwhelming weight of God's declared concern for the poor. This is not a New Testament addition to an otherwise indifferent Hebrew tradition. From the earliest books of the Law, God's care for the marginalised is built into the very structure of Israelite society.\n\nThe gleaning laws of Leviticus and Deuteronomy required that farmers leave the edges of their fields unharvested, so that the poor could come and gather what they needed. This was not charity — it was law. The Sabbath year commanded that debts be released. The Year of Jubilee commanded the restoration of all alienated property to its original family, ensuring that economic inequality could not compound across generations without limit. These were not suggestions for the devout Israelite. They were the terms of the covenant.\n\nThe prophets — Isaiah, Amos, Micah, Jeremiah — return again and again to the sin of oppressing the poor as among the most grievous of national transgressions. Amos's searing indictment of Israel — 'they sell the innocent for silver, and the needy for a pair of sandals' (Amos 2:6) — reveals that God's patience with injustice has a limit, and that economic oppression is not a social issue but a spiritual one.\n\nThe Psalms are saturated with declarations of God's identification with the poor: 'He raises the poor from the dust and lifts the needy from the ash heap' (Psalm 113:7). The same God who rules the universe is intimately concerned with where the hungry will eat tonight. This is not incidental to who God is. It is essential."
         },
         {
            heading: "Jesus and the Poor",
            text: "The ministry of Jesus was characterised by a startling preferential attention to those on the margins of society. His first public proclamation, drawn from Isaiah 61, was a manifesto for the marginalised: 'The Spirit of the Lord is upon Me to proclaim good news to the poor, release to the captives, recovery of sight to the blind, to set at liberty those who are oppressed.'\n\nNote that Jesus does not simply speak of spiritual poverty here. The Greek word used — ptochos — refers to destitution, to those who have nothing. Jesus came for those who have nothing. His incarnation was itself a kind of solidarity with poverty — born in a feeding trough, raised in a tradesman's workshop in an occupied land, with 'nowhere to lay his head' in his adult ministry.\n\nIn the parable of the sheep and the goats (Matthew 25), Jesus makes perhaps His most disturbing claim about the poor. Every person who fed the hungry, gave water to the thirsty, welcomed the stranger, clothed the naked, visited the sick and imprisoned — they were, in so doing, doing it to Jesus Himself. 'Whatever you did for the least of these brothers and sisters of Mine, you did for Me.' And conversely, whatever was withheld — it was withheld from Him.\n\nThis is not a comfortable passage. It does not permit the separation of devotion to Jesus from service to the poor. It brands them inseparable."
         },
         {
            heading: "The Early Church's Response",
            text: "The early church took these commands seriously to a degree that astonished the pagan world around them. The book of Acts records that 'there was no needy person among them, for from time to time those who owned land or houses sold them, brought the money from the sales and put it at the apostles' feet, and it was distributed to anyone who had need' (Acts 4:34-35).\n\nThis was not communism of the modern ideological variety. It was koinonia — the deep communal sharing of a people who had been transformed by the recognition that everything they had was a gift from God, held in trust for the common good. The early church's radical generosity was inseparable from their witnessing life. It was one of the primary reasons the pagan world found the Christian community compelling.\n\nJulian the Apostate, the Roman Emperor who attempted to reverse the Christianisation of the empire in the fourth century, complained in frustration that 'the godless Galileans care not only for their own poor but for ours as well.' Their generosity was a form of evangelism.\n\nGlobal Peace Ministry, in this tradition, understands charity not as an add-on to its spiritual ministry but as integral to it. Dr. Momodu has consistently taught that a ministry that preaches the Gospel without feeding the hungry is offering an incomplete Gospel — one that the hungry and destitute are right to receive with scepticism."
         },
         {
            heading: "The Danger of Prosperity Without Responsibility",
            text: "Scripture does not teach that wealth is sinful. Abraham was wealthy. Solomon was wealthy. Job, before and after his trials, was wealthy. The question is not whether one is prosperous but what one does with prosperity — whether it becomes a tool for service or a fortress of self-protection.\n\nThe parable of the rich man and Lazarus (Luke 16) is one of the most sobering passages in the Gospels. The rich man is not condemned for illegal activity. He is condemned, apparently, for indifference — for living a life of luxury while a hungry man lay at his gate, longing for scraps, and doing nothing.\n\nThe indictment is not that he made the man poor. It is that he did not see him. Or rather, that he chose not to see him. This kind of chosen blindness — the cultivation of an inner life that permits the pain of others to be filtered out, so that it does not disturb our comfort — is one of the spiritual dangers that prosperity uniquely creates.\n\nThe antidote is what Jesus called 'storing up treasures in heaven' — the intentional, disciplined re-directing of resources toward the Kingdom's priorities. The practice of giving generously — tithes, offerings, charitable giving — is not merely a financial discipline. It is a spiritual one. It trains the soul to hold material things loosely, to be what Paul calls a 'cheerful giver' precisely because the giver has been freed from the anxiety of possession."
         },
         {
            heading: "Systemic Justice and Individual Charity",
            text: "One of the important theological distinctions in Christian social ethics is between individual charity and systemic justice — between addressing the immediate needs of the poor and addressing the structural conditions that produce poverty.\n\nBoth matter, and neither is sufficient alone. Individual charity — feeding a hungry person, giving clothing to someone cold, contributing to a crisis fund — addresses the immediate need and is morally required of the Christian. But it does not change the conditions that produced the hunger.\n\nSystemic justice — advocacy for fair wages, equitable access to education and healthcare, trade policies that do not impoverish developing nations for the benefit of wealthy ones, legal protections for migrant workers — addresses the conditions. It is also morally required, and it is deeply Biblical. The prophets were not merely running soup kitchens. They were indicting entire economic and political systems that ground the faces of the poor into the dust.\n\nGlobal Peace Ministry operates in both dimensions. It meets immediate needs through its charitable ministry and it advocates — through Dr. Momodu's lecturing, writing, and public engagement — for a world order more consistent with the Biblical vision of justice and dignity for all."
         },
         {
            heading: "What You Can Do",
            text: "A teaching on poverty and responsibility that ends without practical application has failed its purpose. Here, then, are concrete invitations to action:\n\nGive regularly and generously. Make charitable giving not an occasional impulse but a practised discipline — a first-fruits commitment rather than what remains at the month's end. The Global Peace Ministry's charity work is sustained by regular givers who have chosen to invest in the transformation of lives.\n\nLearn the faces of poverty. Poverty is abstract until it is personal. Volunteer with a local food bank, a homeless shelter, a refugee support service. Allow encounters with people in need to inform not only your giving but your praying and your advocacy.\n\nSpeak up. Poverty is perpetuated in part by the silence of those who could speak. Write to your elected representative about the issues affecting the poor. Use your social media platform to raise awareness. Support organisations doing systemic advocacy.\n\nPray with intention. Include the poor in your regular intercession. Pray for specific nations where poverty is acute. Pray for wisdom for policymakers. Pray for the strength and resources of those doing frontline work with the marginalised.\n\nThe God who raises the poor from the dust has called His people to be among the instruments of that raising. This is not optional. It is the Gospel in practice."
         },
      ]
   },
   "healing-is-for-today": {
      title: "Healing Is For Today: God's Will for Your Health",
      category: "Healing & Faith",
      readTime: "11 min read",
      date: "October 2024",
      image: "/blog-images/healing.png",
      intro: "Among the most contested and yet most personally relevant questions in Christian theology is this: does God still heal today? Is divine healing a reality for contemporary believers, or was it a phenomenon specific to the apostolic era — a sign for a particular moment in history, now suspended until the second coming? Based on over three decades of ministry experience and careful Biblical study, Lord Professor Dr. Kingsley Kebiru Momodu gives an unequivocal answer: yes. God heals today. Healing is not a relic of the past. It is the continuing ministry of Jesus Christ through His Church.",
      body: [
         {
            heading: "The Healing Ministry of Jesus",
            text: "Any serious engagement with the question of divine healing must begin with the Gospels, because the Gospels present an indisputable picture: healing was central to the ministry of Jesus. Not peripheral. Not occasional. Not symbolic. Central.\n\nMatthew's summary statement — 'Jesus went throughout Galilee, teaching in their synagogues, proclaiming the good news of the kingdom, and healing every disease and sickness among the people' (Matthew 4:23) — establishes healing as one of the three defining activities of the Messiah's ministry alongside teaching and proclamation. The healing of the sick was not anecdotal padding to the 'real' spiritual message. It was part of the message. In every act of healing, Jesus was declaring in embodied form what He also declared in word: the Kingdom of God has arrived, and in the Kingdom, bodies are made whole.\n\nThe range of what Jesus healed is breathtaking. Leprosy. Blindness. Deafness. Paralysis. Haemorrhage. Withered limbs. Epilepsy. And death itself — in the cases of Lazarus, the widow's son at Nain, and Jairus's daughter. No condition is presented in the Gospels as beyond the reach of His power. In not a single instance does Jesus tell a sick person, 'It is not the Father's will for you to be well.' In every case where healing is requested in faith, it is given."
         },
         {
            heading: "Healing in the Early Church",
            text: "The critics of divine healing often argue from a cessationist position: that the miraculous gifts of the Spirit, including healing, ceased with the passing of the apostolic generation. But this claim finds no support in the New Testament itself, and is difficult to sustain even historically.\n\nThe book of Acts records healings flowing through the apostles (Acts 3, 5, 9), through non-apostolic figures like Stephen and Philip (Acts 6-8), and through ordinary church members (Acts 9:32-35). The Letter of James — written not to an apostolic elite but to the general church — gives explicit instruction that when any member of the congregation is sick, they should 'call the elders of the church to pray over them and anoint them with oil in the name of the Lord' with the promise that 'the prayer offered in faith will make the sick person well' (James 5:14-15). This is not a special ministry limited to uniquely gifted individuals. It is the Church's ordinary practice.\n\nThe second and third century church fathers — Irenaeus, Tertullian, Origen — all write of healing miracles occurring in their communities as ongoing realities. It was not until the fifth and sixth centuries, when the church had become institutionalised and theologically accommodated to a world in which miracles were embarrassing, that cessationist arguments began to gain significant traction. The history does not support the theology."
         },
         {
            heading: "Is It Always God's Will to Heal?",
            text: "This is the question that causes the most pastoral difficulty, and it deserves honest and careful engagement.\n\nThe consistent testimony of the Gospels is that it was always Jesus's will to heal those who came to Him in faith. The one instance sometimes cited as an exception — the man blind from birth in John 9 — resolves itself on examination: the disciples ask whether the blindness was caused by the man's or his parents' sin; Jesus denies both and says 'this happened so that the works of God might be displayed in him' — and then heals him. Even in the one case where healing is apparently delayed, the resolution is healing.\n\nThe most challenging passage is the Apostle Paul's 'thorn in the flesh' (2 Corinthians 12). Paul prayed three times for its removal; God responded 'My grace is sufficient for you.' Some have read this as biblical evidence that it is sometimes God's will for believers to remain sick. But careful exegesis reveals that Paul does not describe the thorn as a physical illness. Most Biblical scholars understand it as a reference to external opposition or persecution — a 'messenger of Satan' sent to harass him, most likely referring to the ongoing persecution he experienced. It is not at all clear that this passage teaches that God wills chronic illness upon His children.\n\nWhat the Scriptures do affirm is that healing, like all benefits of the Kingdom, exists in the 'already but not yet' tension of Christian eschatology. The Kingdom has broken in; the full completion of the Kingdom has not yet come. In this present age, we sometimes receive the fullness of a Kingdom promise — and sometimes receive grace to endure what has not yet been fully resolved. Both are real experiences. Neither should be used to deny the other."
         },
         {
            heading: "The Relationship Between Faith and Healing",
            text: "Jesus repeatedly made explicit connections between faith and healing. 'Your faith has made you well,' He told the haemorrhaging woman (Mark 5:34), the blind Bartimaeus (Mark 10:52), and the ten lepers (Luke 17:19), among others. When He could not do many miracles in Nazareth, the text explicitly attributes this to the people's unbelief (Matthew 13:58).\n\nThis correlation requires careful handling. It has been misused to produce cruel and spiritually damaging applications: the message that if a believer is not healed, it is because they lack sufficient faith. This teaching devastates people who are already suffering and adds a burden of false guilt to physical pain.\n\nThe alternative — taught in this ministry — is not to deny the relationship between faith and healing but to understand faith rightly. Faith, in the New Testament, is not a quantity of confident feeling. It is a quality of trusting relationship — with a Person, not with a theological proposition about healing. The woman who touched the hem of Jesus's garment was not exercising a principle. She was reaching for Jesus. The blind men who cried 'Son of David, have mercy!' were not applying a formula. They were calling on the Lord.\n\nHealing prayer is therefore not a spiritual technique. It is an encounter — with the living Christ who remains the same yesterday, today, and forever. The prayer of faith is the prayer that genuinely believes that this Person cares, that this Person can act, and that this Person is present in this room, at this bedside, in this moment of need."
         },
         {
            heading: "How to Receive Healing",
            text: "The practical question, for those who are suffering and seeking health, is how to position themselves to receive what God makes available.\n\nDr. Momodu, who has seen significant healings across his ministry in prayer meetings, hospital visits, and remote prayer, offers the following counsel rooted in Scripture and experience:\n\nBegin with confession of sin. James 5 connects healing explicitly with the confession of sin: 'Confess your sins to each other and pray for each other so that you may be healed.' This is not suggesting that all illness is caused by specific sin. It is recognising that a soul right before God is a soul positioned to receive.\n\nBring your need specifically. Vague prayer produces vague faith. Name what you are believing for. Tell God the diagnosis, the prognosis, the fear. He is not surprised by any of it. He has been present in every doctor's consultation, every scan, every sleepless night. Name it before Him, and ask specifically.\n\nInvite the elders or believing community to pray with you. The promise of James 5 is not the private prayer of the sick person alone — it is the prayer of the community surrounding them. Healing prayer is a corporate act.\n\nPersist. The parable of the persistent widow is as applicable to healing prayer as to any other form of intercession. Do not assume that one prayer is the measure of what God will do. Many of the healings in scripture required persistence, faith, and time.\n\nTrust the Healer even when the healing is not immediate. His love for you is not contingent on your health. His purposes for your life are not defeated by your illness. Whatever the outcome, you are held by a God who knows your name, who counts the hairs of your head, and who declares that neither life nor death, neither the present nor the future, can separate you from His love."
         },
         {
            heading: "A Word of Faith",
            text: "Healing is for you. Not because you deserve it. Not because you have prayed enough or believed with sufficient intensity. But because you were made in the image of a God who loves you, who sent His Son specifically so that your every need could be presented at the throne of grace with confidence, and who has not ceased — for one moment of all of human history — to be concerned about the details of your life.\n\nAt Global Peace Ministry, prayer for the sick is not a special service reserved for dramatic occasions. It is woven into every gathering, every outreach, every pastoral encounter, because we understand it to be one of the forms in which Jesus continues His ministry through His body, the Church.\n\nIf you are unwell — in body, in mind, in spirit — you are invited to reach out to this ministry for prayer. You are not a burden. You are the reason Jesus came. And it is our privilege, and our calling, to stand with you in faith for the health that God desires for every one of His children."
         },
      ]
   }
};

export default function BlogPostPage() {
   const params = useParams();
   const slug = params.slug as string;
   const article = articles[slug];

   if (!article) {
      return (
         <div className="min-h-screen bg-cream flex flex-col items-center justify-center px-6 text-center">
            <h1 className="font-serif text-5xl font-bold text-primary-900 mb-6">Article Not Found</h1>
            <p className="text-lg text-primary-900/70 mb-10">This article does not exist or may have been moved.</p>
            <Link href="/blog" className="btn-primary">← Back to Blog</Link>
         </div>
      );
   }

   return (
      <div className="flex flex-col w-full bg-cream min-h-screen">

         {/* Hero */}
         <section className="relative bg-primary-900 text-cream pt-36 pb-32 px-6 md:px-12 overflow-hidden">
            <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top_left,_var(--tw-gradient-stops))] from-primary-600/10 via-transparent to-transparent pointer-events-none" />
            <div className="max-w-4xl mx-auto relative z-10">
               <motion.div {...fadeInUp}>
                  <Link href="/blog" className="inline-flex items-center gap-2 text-light-sage/70 hover:text-light-sage text-sm font-bold uppercase tracking-widest mb-10 transition-colors">
                     <ArrowLeft className="w-4 h-4" />
                     Back to Blog
                  </Link>
                  <div className="flex items-center gap-3 mb-6 text-[11px] font-bold uppercase tracking-[0.25em] text-primary-600">
                     <Tag className="w-3.5 h-3.5" />
                     {article.category}
                  </div>
                  <h1 className="font-serif text-4xl md:text-5xl lg:text-7xl font-bold mb-8 leading-tight">
                     {article.title}
                  </h1>
                  <div className="flex items-center gap-6 text-cream/50 text-sm font-medium">
                     <span className="flex items-center gap-2"><Clock className="w-4 h-4" />{article.readTime}</span>
                     <span className="flex items-center gap-2"><BookOpen className="w-4 h-4" />{article.date}</span>
                  </div>
               </motion.div>
            </div>
         </section>

         {/* Featured Image */}
         <div className="w-full relative z-20 px-6 md:px-12 -mt-16 md:-mt-24">
            <motion.div
               initial={{ opacity: 0, y: 30 }}
               animate={{ opacity: 1, y: 0 }}
               transition={{ duration: 0.8, delay: 0.1 }}
               className="max-w-5xl mx-auto w-full aspect-video md:aspect-[21/9] rounded-2xl overflow-hidden shadow-2xl bg-primary-900/10 border border-muted-teal/20"
            >
               <img src={article.image} alt={article.title} className="w-full h-full object-cover" />
            </motion.div>
         </div>

         {/* Article Body */}
         <article className="pt-16 pb-20 px-6 md:px-12">
            <div className="max-w-3xl mx-auto">
               {/* Intro */}
               <motion.p
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.8, delay: 0.2 }}
                  className="text-xl md:text-2xl text-primary-900 font-medium leading-relaxed mb-16 border-l-4 border-primary-600 pl-8 italic"
               >
                  {article.intro}
               </motion.p>

               {/* Body Sections */}
               <div className="space-y-14">
                  {article.body.map((section, i) => (
                     <motion.div
                        key={i}
                        initial={{ opacity: 0, y: 24 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{ duration: 0.7, delay: i * 0.05 }}
                     >
                        {section.heading && (
                           <h2 className="font-serif text-2xl md:text-3xl font-bold text-primary-900 mb-5">
                              {section.heading}
                           </h2>
                        )}
                        {section.text.split('\n\n').map((para, j) => (
                           <p key={j} className="text-[17px] text-primary-900/80 leading-[1.85] mb-5 font-medium">
                              {para}
                           </p>
                        ))}
                     </motion.div>
                  ))}
               </div>

               {/* Footer CTA */}
               <motion.div
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.8 }}
                  className="mt-24 bg-primary-900 text-cream p-12 md:p-16 rounded-3xl text-center border-t-4 border-primary-600"
               >
                  <h3 className="font-serif text-3xl md:text-4xl font-bold mb-4">Continue Reading</h3>
                  <p className="text-cream/70 text-lg mb-8 max-w-xl mx-auto">
                     Explore more reflections, teachings, and testimonies from Global Peace Ministry.
                  </p>
                  <Link href="/blog" className="btn-secondary !border-primary-600 !text-primary-900 !bg-primary-600 hover:!bg-white inline-block px-10">
                     ← All Articles
                  </Link>
               </motion.div>
            </div>
         </article>
      </div>
   );
}
